sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script:
    - hugo
    - echo 'Hugo build done!'
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: public
    repo: pkptzx/baqi.io
    fqdn: www.baqi.io
    target_branch: master
    email: pkptzx@126.com
    name: pkptzx