# sudo: false
language: go
os:
  - linux
go:
  - "1.14.8"
  - "1.15.1"
  - master
git:
    depth: 1
install: 
    - go get -v github.com/gohugoio/hugo
script:
    - go mod download
    - go mod verify
    - hugo
    - echo 'Hugo build done!'
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: public
    repo: pkptzx/blog
    fqdn: blog.lazy.icu
    target_branch: gh-pages
    email: pkptzx@126.com
    name: pkptzx
