baseURL = "http://blog.lazy.icu"
languageCode = "zh-CN"
title = "码魂"
theme = "maupassant"
summaryLength = 70 

[author]
  name = "码魂"

[params]
  author = "码魂"
  subtitle = "专注于Java、移动互联网、移动支付、项目管理、软件架构"
  keywords = "码魂,java,android,博客,项目管理,微信,软件架构,公众号,小程序"
  description = "专注于IT互联网，包括但不限于专注于Java、移动互联网、移动支付、项目管理、软件架构等"
  busuanzi = true
  beian = "计划中..."
  fancybox = true
  localSearch = true
  
[menu]
  [[menu.main]]
    identifier = "books"
    name = "读书"
    url = "/books/"
    weight = 2
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4

[[params.links]]
  title = "百度"
  name = "百度"
  url = "http://www.baidu.com"
[[params.links]]
  title = "开源中国"
  name = "开源中国"
  url = "http://www.oschina.net"

[params.utteranc]
    enable = true
    repo = "pkptzx/blog"
    issueTerm = "pathname"
    theme = "github-light"
  
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"
    
    
    
    
  
